# Generated by Django 2.0.2 on 2018-02-22 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='horiz',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='vert',
            new_name='y',
        ),
    ]
